version: '2'

networks:
  productionNetwork:
    external: false

volumes:
  konfettiDb:
    external: false

services:
  konfettiBackend:
    image: konfetti/backend
    container_name: konfettiBackend
    ports:
      - "8080:9000"
    networks:
      - productionNetwork
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: docker

  database:
    image: mysql:5.7.12
    container_name: konfettiDb
    ports:
      - "3307:3306"
    networks:
      - productionNetwork
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: konfetti
      MYSQL_USER: konfetti
      MYSQL_PASSWORD: konfetti
    volumes:
      - konfettiDb:/var/lib/mysql